#pragma once

// Include everything — this is all a user needs to #include.
#include "tui/geometry.hpp"
#include "tui/style.hpp"
#include "tui/symbols.hpp"
#include "tui/cell.hpp"
#include "tui/utf8.hpp"
#include "tui/buffer.hpp"
#include "tui/drawable.hpp"
#include "tui/theme.hpp"
#include "tui/block.hpp"
#include "tui/events.hpp"
#include "tui/terminal.hpp"
#include "tui/widgets/paragraph.hpp"
#include "tui/widgets/list.hpp"
#include "tui/widgets/barchart.hpp"
#include "tui/widgets/gauge.hpp"
#include "tui/canvas.hpp"
#include "tui/style_parser.hpp"
#include "tui/widgets/plot.hpp"
#include "tui/widgets/table.hpp"
#include "tui/widgets/sparkline.hpp"
#include "tui/widgets/stacked_barchart.hpp"
#include "tui/widgets/tabs.hpp"
#include "tui/widgets/tree.hpp"
#include "tui/widgets/piechart.hpp"
#include "tui/grid.hpp"
